name: Nightly Builds

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build-main:
    name: Main
    uses: ./.github/workflows/setup-and-test.yml
    with:
      branch: main

  build-start-here:
    name: Start Here
    uses: ./.github/workflows/setup-and-test.yml
    with:
      branch: sample-code/start-here

  build-module-3:
    name: Module 3 My First Playwright Test
    uses: ./.github/workflows/setup-and-test.yml
    with:
      branch: sample-code/module-3-my-first-playwright-test

  build-module-4:
    name: Module 4 Interacting With Elements
    uses: ./.github/workflows/setup-and-test.yml
    with:
      branch: sample-code/module-4-interacting-with-elements

  build-module-5:
    name: Module 5 Simple Refactoring
    uses: ./.github/workflows/setup-and-test.yml
    with:
      branch: sample-code/module-5-refactoring

  build-module-6:
    name: Module 6 Browser Options
    uses: ./.github/workflows/setup-and-test.yml
    with:
      branch: sample-code/module-6-browser-options

  build-module-7:
    name: Module 7 Browser Contexts
    uses: ./.github/workflows/setup-and-test.yml
    with:
      branch: sample-code/module-7-browser-contexts

  build-module-8-live-demo:
    name: Module 8 Live Coding Demo
    uses: ./.github/workflows/setup-and-test.yml
    with:
      branch: sample-code/module-8-live-coding-demo

  build-module-8-locators:
    name: Module 8 Locators
    uses: ./.github/workflows/setup-and-test.yml
    with:
      branch: sample-code/module-8-locators

  build-module-9:
    name: Module 9 Forms and Elements
    uses: ./.github/workflows/setup-and-test.yml
    with:
      branch: sample-code/module-9-forms

  build-module-10:
    name: Module 10 Assertions
    uses: ./.github/workflows/setup-and-test.yml
    with:
      branch: sample-code/module-10-assertions

  build-module-11:
    name: Module 11 Waits
    uses: ./.github/workflows/setup-and-test.yml
    with:
      branch: sample-code/module-11-waits

  build-module-12-api:
    name: Module 12 API Interactions
    uses: ./.github/workflows/setup-and-test.yml
    with:
      branch: sample-code/module-12-api-interactions

  build-module-12-mocking:
    name: Module 12 Mocking API Calls
    uses: ./.github/workflows/setup-and-test.yml
    with:
      branch: sample-code/module-12-mocking-api-calls

  build-module-13:
    name: Module 13 Page Objects
    uses: ./.github/workflows/setup-and-test.yml
    with:
      branch: sample-code/module-13-page-objects

  build-module-14-org:
    name: Module 14 Organizing Tests
    uses: ./.github/workflows/setup-and-test.yml
    with:
      branch: sample-code/module-14-organizing-your-tests

  build-module-14-tracing:
    name: Module 14 Tracing
    uses: ./.github/workflows/setup-and-test.yml
    with:
      branch: sample-code/module-14-tracing

  build-module-15-parallel:
    name: Module 15 Parallel Execution
    uses: ./.github/workflows/setup-and-test.yml
    with:
      branch: sample-code/module-15-parallel-execution

  build-module-15-annotated:
    name: Module 15 Parallel Execution Annotated
    uses: ./.github/workflows/setup-and-test.yml
    with:
      branch: sample-code/module-15-parallel-execution-annotated

  build-module-16:
    name: Module 16 Allure Reporting
    uses: ./.github/workflows/setup-and-test.yml
    with:
      branch: sample-code/module-16-allure-reporting

  build-module-17:
    name: Module 17 Cucumber
    uses: ./.github/workflows/setup-and-test.yml
    with:
      branch: sample-code/module-17-cucumber

  build-module-18:
    name: Module 18 Workflow Tests
    uses: ./.github/workflows/setup-and-test.yml
    with:
      branch: sample-code/module-18-end-to-end

  build-module-20-start:
    name: Module 20 Docker Start
    uses: ./.github/workflows/setup-and-test.yml
    with:
      branch: sample-code/module-20-docker-start

  build-module-20-docker:
    name: Module 20 Docker
    uses: ./.github/workflows/setup-and-test.yml
    with:
      branch: sample-code/module-20-docker
